/**
 * Video Assembly Service
 * Assembles final video from clips, music, and branding using FFmpeg
 */

import fsPromises from 'fs/promises';
import fs from 'fs';
import path from 'path';
import { runFFmpeg, getVideoDuration, checkFFmpeg } from './ffmpeg-utils';
import RedisService from '../../services/redis-service';
import { Readable } from 'stream';
import { pipeline } from 'stream/promises';

export interface VideoAssemblyInput {
    jobId: string;
    videoId: string;
    clips: string[];
    clipTimings?: number[];      // Pre-calculated durations for each clip (from keyword extraction)
    narration?: string;          // Narration text for timing (fallback if no clipTimings)
    narrationAudio?: string;     // Path to narration audio file (generated by Gemini TTS)
    music?: string;
    branding?: {
        logo?: string;
        intro?: string;
        outro?: string;
    };
    isShort?: boolean;           // If true, output vertical 9:16 format for YouTube Shorts
}

export interface VideoAssemblyResult {
    videoId: string;
    outputPath: string;
    duration: number;
    clipCount: number;
}

export class VideoAssemblyService {
    private workDir: string;
    private readonly WORDS_PER_MINUTE = 150; // Average speaking rate
    private readonly WORDS_PER_SECOND = this.WORDS_PER_MINUTE / 60;

    // Video format configurations
    private readonly LANDSCAPE_FORMAT = {
        width: 1920,
        height: 1080,
        scale: 'scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black',
    };

    private readonly VERTICAL_FORMAT = {
        width: 1080,
        height: 1920,
        // For vertical: crop center of landscape video, then scale to 1080x1920
        scale: 'scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920',
    };

    constructor(workDir?: string) {
        this.workDir = workDir || path.join(process.cwd(), 'videos');
    }

    /**
     * Get video filter string based on format (landscape or vertical for shorts)
     */
    private getVideoFilter(isShort: boolean = false): string {
        const format = isShort ? this.VERTICAL_FORMAT : this.LANDSCAPE_FORMAT;
        return `${format.scale},fps=30`;
    }

    /**
     * Calculate duration for narration text (in seconds)
     */
    private calculateNarrationDuration(text: string): number {
        // Remove [PAUSE] markers and count words
        const cleanText = text.replace(/\[PAUSE\]/g, '');
        const wordCount = cleanText.trim().split(/\s+/).filter(w => w.length > 0).length;

        // Count pauses (add 1 second per pause)
        const pauseCount = (text.match(/\[PAUSE\]/g) || []).length;

        // Calculate duration: (words / words_per_second) + (pause_count * 1)
        const duration = (wordCount / this.WORDS_PER_SECOND) + pauseCount;

        return Math.max(duration, 5); // Minimum 5 seconds
    }

    /**
     * Normalize pre-calculated clip timings to match actual audio duration
     * This ensures the total clip duration matches the narration audio exactly
     * 
     * Algorithm:
     * 1. Calculate the difference between total clip duration and target audio duration
     * 2. If clips are too long: reduce each clip proportionally
     * 3. If clips are too short: increase each clip proportionally
     * 4. Ensure minimum duration of 1 second per clip
     */
    private normalizeClipTimingsToAudio(
        clipTimings: number[],
        targetAudioDuration: number
    ): number[] {
        if (clipTimings.length === 0) {
            return [];
        }

        const currentTotal = clipTimings.reduce((sum, t) => sum + t, 0);
        const difference = targetAudioDuration - currentTotal;
        const clipCount = clipTimings.length;

        console.log(`📊 Clip Timing Normalization:`);
        console.log(`   Current total: ${currentTotal.toFixed(2)}s`);
        console.log(`   Target (audio): ${targetAudioDuration.toFixed(2)}s`);
        console.log(`   Difference: ${difference.toFixed(2)}s`);

        if (Math.abs(difference) < 0.1) {
            // Already close enough, no adjustment needed
            console.log(`   ✓ Timings are already synchronized`);
            return clipTimings;
        }

        // Calculate adjustment per clip (proportional to each clip's duration)
        const normalizedTimings = clipTimings.map(timing => {
            // Proportional adjustment: each clip gets adjusted based on its share of total
            const proportion = timing / currentTotal;
            const adjustment = difference * proportion;
            const newTiming = timing + adjustment;

            // Ensure minimum 1 second per clip
            return Math.max(1.0, newTiming);
        });

        // Verify and fine-tune to match exactly
        const newTotal = normalizedTimings.reduce((sum, t) => sum + t, 0);
        if (Math.abs(newTotal - targetAudioDuration) > 0.1) {
            // Distribute remaining difference evenly
            const remainingDiff = targetAudioDuration - newTotal;
            const perClipAdjust = remainingDiff / clipCount;

            for (let i = 0; i < normalizedTimings.length; i++) {
                normalizedTimings[i] = Math.max(1.0, normalizedTimings[i] + perClipAdjust);
            }
        }

        const finalTotal = normalizedTimings.reduce((sum, t) => sum + t, 0);
        console.log(`   Adjusted total: ${finalTotal.toFixed(2)}s`);
        console.log(`   ✓ Timings normalized to match audio duration`);

        return normalizedTimings;
    }

    /**
     * Split narration into segments and calculate timing for each clip
     * This is the fallback method when no pre-calculated timings are provided
     */
    private calculateClipTimings(narration: string, clipCount: number): number[] {
        if (!narration || clipCount === 0) {
            // Fallback to equal distribution of 5 seconds each
            return Array(clipCount).fill(5);
        }

        // Split narration into paragraphs
        const paragraphs = narration.split('\n\n').filter(p => p.trim().length > 0);

        if (paragraphs.length === 0) {
            return Array(clipCount).fill(5);
        }

        // Calculate duration for each paragraph
        const paragraphDurations = paragraphs.map(p => this.calculateNarrationDuration(p));
        const totalNarrationDuration = paragraphDurations.reduce((sum, d) => sum + d, 0);

        console.log(`📊 Narration Analysis (fallback):`);
        console.log(`   Paragraphs: ${paragraphs.length}`);
        console.log(`   Total duration: ${totalNarrationDuration.toFixed(2)}s`);
        console.log(`   Clips: ${clipCount}`);

        // Distribute clips across paragraphs proportionally
        const clipTimings: number[] = [];

        if (paragraphs.length >= clipCount) {
            // More paragraphs than clips: group paragraphs
            const paragraphsPerClip = Math.ceil(paragraphs.length / clipCount);

            for (let i = 0; i < clipCount; i++) {
                const startIdx = i * paragraphsPerClip;
                const endIdx = Math.min(startIdx + paragraphsPerClip, paragraphs.length);
                const clipDuration = paragraphDurations.slice(startIdx, endIdx).reduce((sum, d) => sum + d, 0);
                clipTimings.push(clipDuration);
            }
        } else {
            // More clips than paragraphs: distribute clips across paragraphs
            const clipsPerParagraph = clipCount / paragraphs.length;

            paragraphs.forEach((_, pIdx) => {
                const paragraphDuration = paragraphDurations[pIdx];
                const clipsInThisParagraph = Math.round(clipsPerParagraph);
                const durationPerClip = paragraphDuration / clipsInThisParagraph;

                for (let i = 0; i < clipsInThisParagraph && clipTimings.length < clipCount; i++) {
                    clipTimings.push(durationPerClip);
                }
            });
        }

        // Ensure we have exactly clipCount timings
        while (clipTimings.length < clipCount) {
            clipTimings.push(5);
        }
        while (clipTimings.length > clipCount) {
            clipTimings.pop();
        }

        console.log(`   Clip timings: ${clipTimings.map(t => t.toFixed(1) + 's').join(', ')}`);

        return clipTimings;
    }

    private async downloadFile(url: string, outPath: string) {
        const res = await fetch(url);
        if (!res.ok || !res.body) {
        throw new Error(`Failed to download ${url}`);
        }

        await pipeline(
            Readable.fromWeb(res.body),
            fs.createWriteStream(outPath)
        );
    }

    /**
     * Assemble a complete video from all assets
     */
    async assembleVideo(input: VideoAssemblyInput): Promise<VideoAssemblyResult> {
        const redisService = RedisService.getInstance();

        console.log('\n🎬 === VIDEO ASSEMBLY STARTED ===');
        console.log(`Video ID: ${input.videoId}`);
        console.log(`Clips: ${input.clips.length}`);
        console.log(`Pre-calculated timings: ${input.clipTimings ? '✓' : '✗'}`);
        console.log(`Narration: ${input.narration ? '✓' : '✗'}`);
        console.log(`Narration Audio: ${input.narrationAudio ? '✓' : '✗'}`);
        console.log(`Music: ${input.music ? '✓' : '✗'}`);
        console.log(`Branding: ${input.branding ? Object.keys(input.branding).length : 0} asset(s)`);
        console.log(`Shorts Format: ${input.isShort ? '✓ (9:16 vertical, no intro/outro)' : '✗'}`);

        // Check FFmpeg availability
        const hasFFmpeg = await checkFFmpeg();
        if (!hasFFmpeg) {
            throw new Error('FFmpeg is not installed or not in PATH');
        }

        // Create output directory
        const outputDir = path.join(this.workDir, input.videoId);
        await fsPromises.mkdir(outputDir, { recursive: true });

        const narrationAudioPath = path.join(outputDir, 'narration_audio.mp3');
        if (input.narrationAudio) {
            await this.downloadFile(input.narrationAudio, narrationAudioPath);
        }

        input.narrationAudio = narrationAudioPath;

        // Get actual audio duration if narration audio is provided
        let actualAudioDuration: number | null = null;
        if (input.narrationAudio) {
            try {
                actualAudioDuration = await getVideoDuration(input.narrationAudio);
                console.log(`🎵 Actual narration audio duration: ${actualAudioDuration.toFixed(2)}s`);
            } catch (error) {
                console.warn('⚠️  Could not determine narration audio duration');
            }
        }

        // Determine clip timings
        let clipTimings: number[];

        if (input.clipTimings && input.clipTimings.length === input.clips.length) {
            // Use pre-calculated timings from keyword extraction
            console.log('\n📐 Using pre-calculated clip timings from keyword extraction...');
            console.log(`   Original timings: ${input.clipTimings.map(t => t.toFixed(2) + 's').join(', ')}`);

            // Normalize timings to match actual audio duration
            if (actualAudioDuration) {
                clipTimings = this.normalizeClipTimingsToAudio(input.clipTimings, actualAudioDuration);
            } else {
                clipTimings = input.clipTimings;
            }
        } else {
            // Fallback: calculate timings based on narration text
            console.log('\n📐 Calculating clip timings from narration text (fallback)...');
            clipTimings = this.calculateClipTimings(input.narration || '', input.clips.length);

            // Normalize to actual audio duration if available
            if (actualAudioDuration) {
                clipTimings = this.normalizeClipTimingsToAudio(clipTimings, actualAudioDuration);
            }
        }

        console.log(`   Final timings: ${clipTimings.map(t => t.toFixed(2) + 's').join(', ')}`);
        console.log(`   Total: ${clipTimings.reduce((a, b) => a + b, 0).toFixed(2)}s`);

        // Step 1: Normalize all clips with calculated timing
        console.log('\n📐 Step 1: downloading, Normalizing and concatenating clips with dynamic timing...');
        const mainClipsVideo = await this.normalizeAndConcatClipsWithTiming(input.jobId, input.clips, clipTimings, outputDir, input.isShort);
        console.log(`✅ Normalized & concatenated ${input.clips.length} clips`);

        // Get main clips duration for audio preparation
        const mainClipsDuration = await getVideoDuration(mainClipsVideo);
        console.log(`📊 Main clips duration: ${mainClipsDuration.toFixed(2)}s`);

        // Step 2: Prepare audio (mix narration and background music) for main clips only
        console.log('\n🎵 Step 2: Preparing audio for main clips...');
        let finalAudio: string;
        if (input.narrationAudio && input.music) {
            finalAudio = await this.mixNarrationWithMusic(input.narrationAudio, input.music, mainClipsDuration, outputDir);
            console.log(`✅ Narration and background music mixed`);
        } else if (input.music) {
            finalAudio = await this.prepareBackgroundMusic(input.music, mainClipsDuration, outputDir);
            console.log(`✅ Background music prepared`);
        } else {
            // Generate silence
            finalAudio = path.join(outputDir, 'silence.mp3');
            await this.generatePlaceholderNarration(mainClipsDuration, finalAudio);
            console.log(`✅ Using silence (no music provided)`);
        }

        await redisService.updateJobProgress(input.jobId, 'processing', 75, 'Prepared audio for main clips');

        // Step 3: Add audio to main clips video
        console.log('\n🎬 Step 3: Adding audio to main clips...');
        const mainClipsWithAudio = path.join(outputDir, 'main_clips_with_audio.mp4');
        await this.addAudioToVideo(mainClipsVideo, finalAudio, mainClipsWithAudio);
        console.log(`✅ Audio added to main clips`);

        await redisService.updateJobProgress(input.jobId, 'processing', 80, 'Added audio to main clips');

        let combinedVideo: string;

        // Step 4 & 5: Skip intro/outro for shorts, add them for long-form videos
        if (input.isShort) {
            // For shorts: skip intro/outro entirely
            console.log('\n🎬 Step 4: Skipping intro/outro (shorts format)...');
            console.log(`✅ No intro/outro added for short video`);

            console.log('\n🔗 Step 5: Using main video as combined video...');
            combinedVideo = mainClipsWithAudio;
            console.log(`✅ Main video ready for logo overlay`);
        } else {
            // For long-form: add intro/outro
            console.log('\n🎬 Step 4: Adding intro/outro with original audio...');
            const clipsWithBranding = await this.addIntroOutroWithOriginalAudio(
                mainClipsWithAudio,
                input.branding?.intro,
                input.branding?.outro,
                outputDir
            );
            console.log(`✅ Branding videos processed`);

            // Step 5: Concatenate intro + main + outro
            console.log('\n🔗 Step 5: Concatenating final video...');
            combinedVideo = path.join(outputDir, 'combined.mp4');
            await this.concatClips(clipsWithBranding, combinedVideo);
            console.log(`✅ Created combined video`);
        }

        await redisService.updateJobProgress(input.jobId, 'processing', 90, 'Combined all video segments');

        // Get total video duration
        const videoDuration = await getVideoDuration(combinedVideo);
        console.log(`📊 Total video duration: ${videoDuration.toFixed(2)}s`);

        // Step 6: Overlay logo (for both shorts and long-form)
        console.log('\n🎨 Step 6: Overlaying logo...');
        const finalOutput = path.join(outputDir, 'final.mp4');
        await this.overlayLogo(combinedVideo, input.branding?.logo, finalOutput);
        console.log(`✅ Logo overlay complete`);

        console.log('\n✅ === VIDEO ASSEMBLY COMPLETE ===');
        console.log(`📁 Output: ${finalOutput}`);
        console.log(`⏱️  Duration: ${videoDuration.toFixed(2)}s`);
        console.log(`🎞️  Clips: ${input.clips.length}`);
        if (input.isShort) {
            console.log(`📱 Format: 9:16 vertical (YouTube Shorts)`);
        }


        return {
            videoId: input.videoId,
            outputPath: `${input.videoId}/final.mp4`, // Path relative to videos/ directory
            duration: videoDuration,
            clipCount: input.clips.length,
        };
    }

    /**
     * Normalize clips with specific timing for each clip
     */
    async normalizeAndConcatClipsWithTiming(
        jobId: string,
        clips: string[],
        timings: number[],
        outputDir: string,
        isShort: boolean = false
    ): Promise<string> {
        const redisService = RedisService.getInstance();

        const normalizedDir = path.join(outputDir, 'normalized');
        await fsPromises.mkdir(normalizedDir, { recursive: true });

        const downloadDir = path.join(outputDir, 'downloads');
        await fsPromises.mkdir(downloadDir, { recursive: true });

        const combinedVideoPath = path.join(outputDir, 'combined_clips.mp4');

        for (let i = 0; i < clips.length; i++) {
            const clipUrl = clips[i];
            const clipPath = path.join(downloadDir, `clip_${i + 1}.mp4`);

            console.log(`  Downloading clip ${i + 1}/${clips.length} from ${clipUrl}...`);
            await this.downloadFile(clipUrl, clipPath);
            const targetDuration = timings[i];
            const outputPath = path.join(normalizedDir, `clip_${i + 1}.mp4`);

            console.log(`  Normalizing clip ${i + 1}/${clips.length} (target: ${targetDuration.toFixed(2)}s)...`);
            await this.normalizeClipWithDuration(clipPath, outputPath, targetDuration, isShort);
            await fsPromises.unlink(clipPath); // Delete downloaded clip after normalization

            // Concatenate to combined video
            if (i > 0) {
                const tempCombinedPath = path.join(outputDir, `temp_combined_${i + 1}.mp4`);
                await this.concatClips([combinedVideoPath, outputPath], tempCombinedPath);
                await fsPromises.copyFile(tempCombinedPath, combinedVideoPath);
                await fsPromises.unlink(tempCombinedPath);
            }
            else await fsPromises.copyFile(outputPath, combinedVideoPath);

            await redisService.updateJobProgress(jobId, 'processing',
                10 + Math.floor(((i + 1) / clips.length) * 60),
                `Normalized and added clip ${i + 1} of ${clips.length}`
            );
        }

        return combinedVideoPath;
    }

    /**
     * Normalize a clip to specific duration
     */
    async normalizeClipWithDuration(
        inputPath: string,
        outputPath: string,
        targetDuration: number,
        isShort: boolean = false
    ): Promise<void> {
        // Get original duration
        let originalDuration: number;
        try {
            originalDuration = await getVideoDuration(inputPath);
        } catch (error) {
            console.warn(`  Could not get duration for ${inputPath}, using target duration`);
            originalDuration = targetDuration;
        }

        const videoFilter = this.getVideoFilter(isShort);

        if (originalDuration < targetDuration) {
            // Clip is too short, loop it
            console.log(`    Looping clip from ${originalDuration.toFixed(2)}s to ${targetDuration.toFixed(2)}s`);
            await runFFmpeg({
                inputs: [
                    { flags: ['-stream_loop', '-1'], path: inputPath }
                ],
                output: outputPath,
                args: [
                    '-t', targetDuration.toString(),
                    '-vf', videoFilter,
                    '-c:v', 'libx264',
                    '-preset', 'medium',
                    '-crf', '23',
                    '-c:a', 'aac',
                    '-b:a', '128k',
                    '-ar', '48000',
                    '-movflags', '+faststart',
                ],
            });
        } else {
            // Clip is long enough, trim to target duration
            console.log(`    Trimming clip from ${originalDuration.toFixed(2)}s to ${targetDuration.toFixed(2)}s`);
            await runFFmpeg({
                inputs: [inputPath],
                output: outputPath,
                args: [
                    '-t', targetDuration.toString(),
                    '-vf', videoFilter,
                    '-c:v', 'libx264',
                    '-preset', 'medium',
                    '-crf', '23',
                    '-c:a', 'aac',
                    '-b:a', '128k',
                    '-ar', '48000',
                    '-movflags', '+faststart',
                ],
            });
        }
    }

    /**
     * Normalize a clip to 1920x1080 (for intro/outro without specific duration)
     */
    async normalizeClip(inputPath: string, outputPath: string): Promise<void> {
        await runFFmpeg({
            inputs: [inputPath],
            output: outputPath,
            args: [
                '-vf', 'scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black,fps=30',
                '-c:v', 'libx264',
                '-preset', 'medium',
                '-crf', '23',
                '-c:a', 'aac',
                '-b:a', '128k',
                '-ar', '48000',
                '-movflags', '+faststart',
            ],
        });
    }

    /**
     * Add intro and outro videos to the clip list
     */
    async addIntroOutro(
        clips: string[],
        introPath: string | undefined,
        outroPath: string | undefined,
        outputDir: string
    ): Promise<string[]> {
        const result: string[] = [];

        // Normalize intro if exists
        if (introPath) {
            const normalizedIntro = path.join(outputDir, 'normalized', 'intro.mp4');
            console.log('  Normalizing intro video...');
            await this.normalizeClip(introPath, normalizedIntro);
            result.push(normalizedIntro);
            console.log('  ✓ Intro added');
        }

        // Add main clips
        result.push(...clips);

        // Normalize outro if exists
        if (outroPath) {
            const normalizedOutro = path.join(outputDir, 'normalized', 'outro.mp4');
            console.log('  Normalizing outro video...');
            await this.normalizeClip(outroPath, normalizedOutro);
            result.push(normalizedOutro);
            console.log('  ✓ Outro added');
        }

        return result;
    }

    /**
     * Add intro and outro videos while preserving their original audio
     * Takes the main video (already with audio) and adds intro/outro around it
     */
    async addIntroOutroWithOriginalAudio(
        mainVideoPath: string,
        introPath: string | undefined,
        outroPath: string | undefined,
        outputDir: string
    ): Promise<string[]> {
        const result: string[] = [];

        // Normalize intro if exists (keeping original audio)
        if (introPath) {
            const normalizedIntro = path.join(outputDir, 'normalized', 'intro.mp4');
            console.log('  Normalizing intro video (preserving original audio)...');
            await this.normalizeClipWithAudio(introPath, normalizedIntro);
            result.push(normalizedIntro);
            console.log('  ✓ Intro added with original audio');
        }

        // Add main video (already has narration + music)
        result.push(mainVideoPath);

        // Normalize outro if exists (keeping original audio)
        if (outroPath) {
            const normalizedOutro = path.join(outputDir, 'normalized', 'outro.mp4');
            console.log('  Normalizing outro video (preserving original audio)...');
            await this.normalizeClipWithAudio(outroPath, normalizedOutro);
            result.push(normalizedOutro);
            console.log('  ✓ Outro added with original audio');
        }

        return result;
    }

    /**
     * Normalize a clip to 1920x1080 while preserving original audio
     */
    async normalizeClipWithAudio(inputPath: string, outputPath: string): Promise<void> {
        await runFFmpeg({
            inputs: [inputPath],
            output: outputPath,
            args: [
                '-vf', 'scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black,fps=30',
                '-c:v', 'libx264',
                '-preset', 'medium',
                '-crf', '23',
                '-c:a', 'aac',
                '-b:a', '192k',
                '-ar', '48000',
                '-movflags', '+faststart',
            ],
        });
    }

    /**
     * Prepare background music - loop to match video duration
     */
    async prepareBackgroundMusic(
        musicPath: string,
        videoDuration: number,
        outputDir: string
    ): Promise<string> {
        const outputPath = path.join(outputDir, 'background_music.mp3');

        console.log(`  Preparing background music to loop for ${videoDuration.toFixed(2)}s...`);

        // Always loop the music to match video duration
        await runFFmpeg({
            inputs: [musicPath],
            output: outputPath,
            args: [
                '-filter_complex', `aloop=loop=-1:size=2e+09,atrim=0:${videoDuration}`,
                '-c:a', 'libmp3lame',
                '-b:a', '192k',
                '-ar', '48000',
            ],
        });

        console.log('  ✓ Background music looped to match video duration');
        return outputPath;
    }

    /**
     * Mix narration audio with background music
     * Narration is primary, music is lowered to background level
     * Music loops throughout entire video with different volume for outro
     */
    async mixNarrationWithMusic(
        narrationPath: string,
        musicPath: string,
        videoDuration: number,
        outputDir: string
    ): Promise<string> {
        const outputPath = path.join(outputDir, 'final_audio.mp3');

        console.log(`  Mixing narration with background music...`);
        console.log(`  Narration: ${narrationPath}`);
        console.log(`  Music: ${musicPath}`);

        // Get narration duration
        const narrationDuration = await getVideoDuration(narrationPath);
        console.log(`  Narration duration: ${narrationDuration.toFixed(2)}s`);
        console.log(`  Total video duration: ${videoDuration.toFixed(2)}s`);

        // Calculate outro duration (time after narration ends)
        const outroDuration = Math.max(0, videoDuration - narrationDuration);
        console.log(`  Outro duration: ${outroDuration.toFixed(2)}s`);

        // Create filter complex for proper audio mixing:
        // 1. Loop music throughout entire video
        // 2. BGM at 15% during narration
        // 3. BGM at 30% during outro (after narration ends)
        const filterComplex = outroDuration > 0
            ? `[1:a]aloop=loop=-1:size=2e+09,atrim=0:${videoDuration}[music];` +
            `anullsrc=r=48000:cl=stereo,atrim=0:${outroDuration}[silence];` +
            `[0:a][silence]concat=n=2:v=0:a=1[narration_padded];` +
            `[music]asplit=2[music1][music2];` +
            `[music1]volume=0.15,atrim=0:${narrationDuration}[bgm_narration];` +
            `[music2]volume=0.30,atrim=${narrationDuration}:${videoDuration},asetpts=PTS-STARTPTS[bgm_outro];` +
            `[narration_padded][bgm_narration]amix=inputs=2:duration=first[main];` +
            `[main][bgm_outro]concat=n=2:v=0:a=1[out]`
            : `[1:a]aloop=loop=-1:size=2e+09,atrim=0:${videoDuration},volume=0.15[music];` +
            `[0:a][music]amix=inputs=2:duration=first[out]`;

        await runFFmpeg({
            inputs: [narrationPath, musicPath],
            output: outputPath,
            args: [
                '-filter_complex', filterComplex,
                '-map', '[out]',
                '-c:a', 'libmp3lame',
                '-b:a', '192k',
                '-ar', '48000',
            ],
        });

        console.log(`  ✓ Audio mixing complete (BGM loops throughout, louder at outro)`);
        return outputPath;
    }

    /**
     * Concatenate multiple clips into one video with smooth transitions
     */
    async concatClips(clips: string[], outputPath: string): Promise<void> {
        if (clips.length === 0) {
            throw new Error('No clips to concatenate');
        }

        if (clips.length === 1) {
            // Only one clip, just copy it
            await fsPromises.copyFile(clips[0], outputPath);
            return;
        }

        console.log(`  Concatenating ${clips.length} clips with crossfade transitions...`);

        // Use simpler concatenation with proper re-encoding for smooth playback
        const concatListPath = path.join(path.dirname(outputPath), 'concat_list.txt');
        const concatList = clips.map(clip => `file '${clip}'`).join('\n');
        await fsPromises.writeFile(concatListPath, concatList);

        // Use concat protocol with re-encoding for smooth transitions
        await runFFmpeg({
            inputs: [],
            output: outputPath,
            args: [
                '-f', 'concat',
                '-safe', '0',
                '-i', concatListPath,
                '-c:v', 'libx264',
                '-preset', 'medium',
                '-crf', '23',
                '-c:a', 'aac',
                '-b:a', '192k',
                '-movflags', '+faststart',
            ],
        });

        console.log('  ✓ Clips concatenated smoothly');
    }

    /**
     * Generate placeholder narration (silence) for the given duration
     */
    async generatePlaceholderNarration(duration: number, outputPath: string): Promise<void> {
        await runFFmpeg({
            inputs: [],
            output: outputPath,
            args: [
                '-f', 'lavfi',
                '-i', `anullsrc=r=44100:cl=stereo`,
                '-t', duration.toString(),
                '-c:a', 'libmp3lame',
                '-b:a', '128k',
            ],
        });
    }

    /**
     * Add audio track to video (replaces existing audio)
     */
    async addAudioToVideo(
        videoPath: string,
        audioPath: string,
        outputPath: string
    ): Promise<void> {
        await runFFmpeg({
            inputs: [videoPath, audioPath],
            output: outputPath,
            args: [
                '-map', '0:v',      // Take video from first input
                '-map', '1:a',      // Take audio from second input (narration + music)
                '-c:v', 'copy',
                '-c:a', 'aac',
                '-b:a', '192k',
                '-shortest',
            ],
        });
    }

    /**
     * Overlay logo on video
     */
    async overlayLogo(
        videoPath: string,
        logoPath: string | undefined,
        outputPath: string
    ): Promise<void> {
        if (!logoPath) {
            // No logo, just copy the video
            await fsPromises.copyFile(videoPath, outputPath, fs.constants.COPYFILE_EXCL);
            console.log('  No logo provided, skipping overlay');
            return;
        }

        // Check if logo file exists
        try {
            await fsPromises.access(logoPath, fs.constants.F_OK);
        } catch (error) {
            console.warn('  Logo file not found, skipping overlay');
            await fsPromises.copyFile(videoPath, outputPath, fs.constants.COPYFILE_EXCL);
            return;
        }

        console.log(`  Applying logo overlay from: ${logoPath}`);

        // Overlay logo at top-right corner with 20px padding
        await runFFmpeg({
            inputs: [videoPath, logoPath],
            output: outputPath,
            args: [
                '-filter_complex',
                '[1:v]scale=150:-1[logo];[0:v][logo]overlay=W-w-20:20',
                '-c:a', 'copy',
                '-c:v', 'libx264',
                '-preset', 'medium',
                '-crf', '23',
            ],
        });

        console.log('  ✓ Logo overlay applied');
    }
}

export default VideoAssemblyService;
