/**
 * Video Assembly Service
 * Assembles final video from clips, music, and branding using FFmpeg
 */

import fsPromises from 'fs/promises';
import fs from 'fs';
import path from 'path';
import { runFFmpeg, getVideoDuration, checkFFmpeg } from './ffmpeg-utils';
import { Readable } from 'stream';
import { pipeline } from 'stream/promises';
import { ReadableStream } from 'stream/web'; // ADD THIS

export interface VideoAssemblyInput {
    jobId: string;
    videoId: string;
    clips: string[];
    clipTimings?: number[];
    animationStopTimes?: number[]; // Pre-calculated durations for each clip (from keyword extraction)
    narration?: string;          // Narration text for timing (fallback if no clipTimings)
    perSceneNarration: string[]; // Narration text per scene (for splitting audio if needed)
    narrationAudios?: string[];     // Path to narration audio file (generated by Gemini TTS)
    music?: string;
    branding?: {
        logo?: string;
        intro?: string;
        outro?: string;
    };
    isShort?: boolean;           // If true, output vertical 9:16 format for YouTube Shorts
}

export interface VideoAssemblyResult {
    videoId: string;
    outputPath: string;
    duration: number;
    clipCount: number;
}

export class VideoAssemblyService {
    private workDir: string;

    // Video format configurations
    private readonly LANDSCAPE_FORMAT = {
        width: 1920,
        height: 1080,
        scale: 'scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black',
    };

    private readonly VERTICAL_FORMAT = {
        width: 1080,
        height: 1920,
        // For vertical: crop center of landscape video, then scale to 1080x1920
        scale: 'scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920',
    };

    constructor(workDir?: string) {
        this.workDir = workDir || path.join(process.cwd(), 'videos');
    }

    /**
     * Get video filter string based on format (landscape or vertical for shorts)
     */
    private getVideoFilter(isShort: boolean = false): string {
        const format = isShort ? this.VERTICAL_FORMAT : this.LANDSCAPE_FORMAT;
        return `${format.scale},fps=30`;
    }

    private async downloadFile(url: string, outPath: string) {
        const res = await fetch(url);
        if (!res.ok || !res.body) {
            throw new Error(`Failed to download ${url}`);
        }

        const webStream = res.body as unknown as ReadableStream;

        await pipeline(
            Readable.fromWeb(webStream),
            fs.createWriteStream(outPath)
        );
    }

    /**
     * Assemble a complete video from all assets
     */
    async assembleVideo(input: VideoAssemblyInput): Promise<VideoAssemblyResult> {
        console.log(`Starting video assembly for ${input.videoId}...`);

        const outputDir = path.join(this.workDir, input.videoId);
        await fsPromises.mkdir(outputDir, { recursive: true });

        console.log(`Number of narration audios: ${input.narrationAudios?.length}`);
        console.log(`Narration audios: ${input.narrationAudios}`);
        if (!input.narrationAudios || input.narrationAudios.length === 0) throw new Error("Narration audios required");

        /* -----------------------------------------
            2. Process each clip and concat on-the-fly
        ------------------------------------------ */
        const combinedPath = path.join(outputDir, "combined_video.mp4");
        let combinedExists = false;

        for (let i = 0; i < input.clips.length; i++) {

            const clipUrl = input.clips[i];

            const clipPath = path.join(outputDir, `clip_${i}.mp4`);
            const sceneAudio = path.join(outputDir, `scene_audio_${i}.wav`);
            const sceneVideo = path.join(outputDir, `scene_video_${i}.mp4`);

            // Download clip
            await this.downloadFile(clipUrl, clipPath);

            // Extract scene audio
            await this.downloadFile(input.narrationAudios[i], sceneAudio);

            const sceneAudioDuration = await getVideoDuration(sceneAudio);
            const animationStop = input.animationStopTimes?.[i] ?? 0;
            const targetDuration = Math.max(animationStop + 0.5, sceneAudioDuration);

            // Normalize clip to target duration
            await this.normalizeClipWithDuration(
                clipPath,
                sceneVideo,
                targetDuration,
                input.isShort
            );

            // Attach audio to scene clip
            const sceneWithAudio = path.join(outputDir, `scene_with_audio_${i}.mp4`);
            await this.addAudioToVideo(sceneVideo, sceneAudio, sceneWithAudio);

            // Concat immediately
            if (!combinedExists) {
                await fsPromises.copyFile(sceneWithAudio, combinedPath);
                combinedExists = true;
            } else {
                const temp = path.join(outputDir, `temp_concat_${i}.mp4`);
                await this.concatClips([combinedPath, sceneWithAudio], temp);
                await fsPromises.rename(temp, combinedPath);
            }

            // Cleanup aggressively
            await Promise.allSettled([
                fsPromises.unlink(clipPath),
                fsPromises.unlink(sceneAudio),
                fsPromises.unlink(sceneVideo),
                fsPromises.unlink(sceneWithAudio),
            ]);
        }

        /* -------------------------
            3. Add background music
        -------------------------- */


        const combinedDuration = await getVideoDuration(combinedPath);
        let finalAudio: string;

        if (input.music) {
            finalAudio = await this.prepareBackgroundMusic(
                input.music,
                combinedDuration,
                outputDir
            );
        } else {
            finalAudio = path.join(outputDir, "silence.mp3");
            await this.generatePlaceholderNarration(combinedDuration, finalAudio);
        }

        const combinedWithMusic = path.join(outputDir, "combined_with_music.mp4");

        await runFFmpeg({
            inputs: [combinedPath, finalAudio],
            output: combinedWithMusic,
            args: [
                "-threads", "1",
                "-filter_complex",
                "[0:a]aresample=48000,pan=stereo|c0=c0|c1=c0[a0];" +
                "[1:a]aresample=48000,pan=stereo|c0=c0|c1=c1[a1];" +
                "[a0][a1]amix=inputs=2:weights=1 0.1:duration=first[a]",
                "-map", "0:v",
                "-map", "[a]",
                "-c:v", "copy",
                "-c:a", "aac",
                "-ar", "48000",
                "-ac", "2",
                "-b:a", "192k",
                "-shortest"
            ],
        });



        /* -------------------------
            4. Intro / Outro
        -------------------------- */


        const normalizedDir = path.join(outputDir, 'normalized');
        await fsPromises.mkdir(normalizedDir, { recursive: true });

        let finalVideo = combinedWithMusic;

        if (!input.isShort && (input.branding?.intro || input.branding?.outro)) {
            const clips = await this.addIntroOutroWithOriginalAudio(
                combinedWithMusic,
                input.branding?.intro,
                input.branding?.outro,
                outputDir
            );

            const withBranding = path.join(outputDir, "with_branding.mp4");
            await this.concatClips(clips, withBranding);
            finalVideo = withBranding;
        }

        /* -------------------------
            5. Logo (optional)
        -------------------------- */


        const finalOutput = path.join(outputDir, "final.mp4");
        if (input.isShort) {
            await this.overlayLogo(finalVideo, input.branding?.logo, finalOutput);
        } else {
            await fsPromises.copyFile(finalVideo, finalOutput);
        }

        const duration = await getVideoDuration(finalOutput);

        return {
            videoId: input.videoId,
            outputPath: `${input.videoId}/final.mp4`,
            duration,
            clipCount: input.clips.length,
        };
    }

    /**
     * Normalize clips with specific timing for each clip
     */
    async normalizeAndConcatClipsWithTiming(
        jobId: string,
        clips: string[],
        timings: number[],
        outputDir: string,
        isShort: boolean = false
    ): Promise<string> {

        const normalizedDir = path.join(outputDir, 'normalized');
        await fsPromises.mkdir(normalizedDir, { recursive: true });

        const downloadDir = path.join(outputDir, 'downloads');
        await fsPromises.mkdir(downloadDir, { recursive: true });

        const combinedVideoPath = path.join(outputDir, 'combined_clips.mp4');

        for (let i = 0; i < clips.length; i++) {
            const clipUrl = clips[i];
            const clipPath = path.join(downloadDir, `clip_${i + 1}.mp4`);

            console.log(`  Downloading clip ${i + 1}/${clips.length} from ${clipUrl}...`);
            await this.downloadFile(clipUrl, clipPath);
            const targetDuration = timings[i];
            const outputPath = path.join(normalizedDir, `clip_${i + 1}.mp4`);

            console.log(`  Normalizing clip ${i + 1}/${clips.length} (target: ${targetDuration.toFixed(2)}s)...`);
            await this.normalizeClipWithDuration(clipPath, outputPath, targetDuration, isShort);
            await fsPromises.unlink(clipPath); // Delete downloaded clip after normalization

            // Concatenate to combined video
            if (i > 0) {
                const tempCombinedPath = path.join(outputDir, `temp_combined_${i + 1}.mp4`);
                await this.concatClips([combinedVideoPath, outputPath], tempCombinedPath);
                await fsPromises.copyFile(tempCombinedPath, combinedVideoPath);
                await fsPromises.unlink(tempCombinedPath);
            }
            else await fsPromises.copyFile(outputPath, combinedVideoPath);

            await fsPromises.unlink(outputPath); // Delete normalized clip after concatenation
        }

        return combinedVideoPath;
    }

    async normalizeClipWithDuration(
        inputPath: string,
        outputPath: string,
        targetDuration: number,
        isShort: boolean = false
    ): Promise<void> {
        const videoFilter = this.getVideoFilter(isShort);

        let originalDuration: number;
        try {
            originalDuration = await getVideoDuration(inputPath);
        } catch {
            originalDuration = targetDuration;
        }

        const needsExtension = originalDuration < targetDuration;
        const extraDuration = Math.max(0, targetDuration - originalDuration);

        const vf = needsExtension
            ? `${videoFilter},tpad=stop_mode=clone:stop_duration=${extraDuration}`
            : videoFilter;

        await runFFmpeg({
            inputs: [inputPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-t', targetDuration.toString(),
                '-vf', vf,
                '-c:v', 'libx264',
                '-x264-params', 'threads=1',
                '-preset', 'veryfast',
                '-crf', '23',
                '-an', // no audio for stock clips
                '-movflags', '+faststart',
            ],
        });
    }

    async normalizeClip(inputPath: string, outputPath: string): Promise<void> {
        await runFFmpeg({
            inputs: [inputPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-vf', 'scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black,fps=30',
                '-c:v', 'libx264',
                '-x264-params', 'threads=1',
                '-preset', 'veryfast',
                '-crf', '23',
                '-c:a', 'aac',
                '-b:a', '128k',
                '-movflags', '+faststart',
            ],
        });
    }


    /**
     * Add intro and outro videos to the clip list
     */
    async addIntroOutro(
        clips: string[],
        introPath: string | undefined,
        outroPath: string | undefined,
        outputDir: string
    ): Promise<string[]> {
        const result: string[] = [];

        // Normalize intro if exists
        if (introPath) {
            const normalizedIntro = path.join(outputDir, 'normalized', 'intro.mp4');
            console.log('  Normalizing intro video...');
            await this.normalizeClip(introPath, normalizedIntro);
            result.push(normalizedIntro);
            console.log('  ✓ Intro added');
        }

        // Add main clips
        result.push(...clips);

        // Normalize outro if exists
        if (outroPath) {
            const normalizedOutro = path.join(outputDir, 'normalized', 'outro.mp4');
            console.log('  Normalizing outro video...');
            await this.normalizeClip(outroPath, normalizedOutro);
            result.push(normalizedOutro);
            console.log('  ✓ Outro added');
        }

        return result;
    }

    /**
     * Add intro and outro videos while preserving their original audio
     * Takes the main video (already with audio) and adds intro/outro around it
     */
    async addIntroOutroWithOriginalAudio(
        mainVideoPath: string,
        introPath: string | undefined,
        outroPath: string | undefined,
        outputDir: string
    ): Promise<string[]> {
        const result: string[] = [];

        // Normalize intro if exists (keeping original audio)
        if (introPath) {
            const normalizedIntro = path.join(outputDir, 'normalized', 'intro.mp4');
            console.log('  Normalizing intro video (preserving original audio)...');
            await this.normalizeClipWithAudio(introPath, normalizedIntro);
            result.push(normalizedIntro);
            console.log('  ✓ Intro added with original audio');
        }

        // Add main video (already has narration + music)
        result.push(mainVideoPath);

        // Normalize outro if exists (keeping original audio)
        if (outroPath) {
            const normalizedOutro = path.join(outputDir, 'normalized', 'outro.mp4');
            console.log('  Normalizing outro video (preserving original audio)...');
            await this.normalizeClipWithAudio(outroPath, normalizedOutro);
            result.push(normalizedOutro);
            console.log('  ✓ Outro added with original audio');
        }

        return result;
    }

    /**
     * Normalize a clip to 1920x1080 while preserving original audio
     */
    async normalizeClipWithAudio(inputPath: string, outputPath: string): Promise<void> {
        await runFFmpeg({
            inputs: [inputPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-vf', 'scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black,fps=30',
                '-c:v', 'libx264',
                '-preset', 'medium',
                '-crf', '23',
                '-c:a', 'aac',
                '-b:a', '192k',
                '-ar', '48000',
                '-ac', '2',
                '-movflags', '+faststart',
            ],
        });
    }


    /**
     * Prepare background music - loop to match video duration
     */
    async prepareBackgroundMusic(
        musicPath: string,
        videoDuration: number,
        outputDir: string
    ): Promise<string> {
        const outputPath = path.join(outputDir, 'background_music.mp3');

        console.log(`  Preparing background music to loop for ${videoDuration.toFixed(2)}s...`);

        // Always loop the music to match video duration
        await runFFmpeg({
            inputs: [musicPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-filter_complex', `aloop=loop=-1:size=2e+09,atrim=0:${videoDuration}`,
                '-c:a', 'libmp3lame',
                '-b:a', '192k',
                '-ar', '48000',
            ],
        });

        console.log('  ✓ Background music looped to match video duration');
        return outputPath;
    }

    /**
     * Mix narration audio with background music
     * Narration is primary, music is lowered to background level
     * Music loops throughout entire video with different volume for outro
     */
    async mixNarrationWithMusic(
        narrationPath: string,
        musicPath: string,
        videoDuration: number,
        outputDir: string
    ): Promise<string> {
        const outputPath = path.join(outputDir, 'final_audio.mp3');

        console.log(`  Mixing narration with background music...`);
        console.log(`  Narration: ${narrationPath}`);
        console.log(`  Music: ${musicPath}`);

        // Get narration duration
        const narrationDuration = await getVideoDuration(narrationPath);
        console.log(`  Narration duration: ${narrationDuration.toFixed(2)}s`);
        console.log(`  Total video duration: ${videoDuration.toFixed(2)}s`);

        // Calculate outro duration (time after narration ends)
        const outroDuration = Math.max(0, videoDuration - narrationDuration);
        console.log(`  Outro duration: ${outroDuration.toFixed(2)}s`);

        // Create filter complex for proper audio mixing:
        // 1. Loop music throughout entire video
        // 2. BGM at 15% during narration
        // 3. BGM at 30% during outro (after narration ends)
        const filterComplex = outroDuration > 0
            ? `[1:a]aloop=loop=-1:size=2e+09,atrim=0:${videoDuration}[music];` +
            `anullsrc=r=48000:cl=stereo,atrim=0:${outroDuration}[silence];` +
            `[0:a][silence]concat=n=2:v=0:a=1[narration_padded];` +
            `[music]asplit=2[music1][music2];` +
            `[music1]volume=0.15,atrim=0:${narrationDuration}[bgm_narration];` +
            `[music2]volume=0.30,atrim=${narrationDuration}:${videoDuration},asetpts=PTS-STARTPTS[bgm_outro];` +
            `[narration_padded][bgm_narration]amix=inputs=2:duration=first[main];` +
            `[main][bgm_outro]concat=n=2:v=0:a=1[out]`
            : `[1:a]aloop=loop=-1:size=2e+09,atrim=0:${videoDuration},volume=0.15[music];` +
            `[0:a][music]amix=inputs=2:duration=first[out]`;

        await runFFmpeg({
            inputs: [narrationPath, musicPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-filter_complex', filterComplex,
                '-map', '[out]',
                '-c:a', 'libmp3lame',
                '-b:a', '192k',
                '-ar', '48000',
            ],
        });

        console.log(`  ✓ Audio mixing complete (BGM loops throughout, louder at outro)`);
        return outputPath;
    }

    async concatClips(clips: string[], outputPath: string): Promise<void> {
        if (clips.length === 0) {
            throw new Error('No clips to concatenate');
        }

        if (clips.length === 1) {
            await fsPromises.copyFile(clips[0], outputPath);
            return;
        }

        const concatListPath = path.join(path.dirname(outputPath), 'concat_list.txt');
        const concatList = clips.map(c => `file '${c}'`).join('\n');
        await fsPromises.writeFile(concatListPath, concatList);

        await runFFmpeg({
            inputs: [],
            output: outputPath,
            args: [
                '-threads', '1',
                '-f', 'concat',
                '-safe', '0',
                '-i', concatListPath,
                '-c:v', 'libx264',
                '-x264-params', 'threads=1',
                '-preset', 'veryfast',
                '-crf', '23',
                '-c:a', 'aac',
                '-b:a', '128k',
                '-movflags', '+faststart',
            ],
        });
    }

    /**
     * Generate placeholder narration (silence) for the given duration
     */
    async generatePlaceholderNarration(duration: number, outputPath: string): Promise<void> {
        await runFFmpeg({
            inputs: [],
            output: outputPath,
            args: [
                '-threads', '1',
                '-f', 'lavfi',
                '-i', `anullsrc=r=44100:cl=stereo`,
                '-t', duration.toString(),
                '-c:a', 'libmp3lame',
                '-b:a', '128k',
            ],
        });
    }

    /**
     * Add audio track to video (replaces existing audio)
     */
    async addAudioToVideo(
        videoPath: string,
        audioPath: string,
        outputPath: string
    ): Promise<void> {
        await runFFmpeg({
            inputs: [videoPath, audioPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-map', '0:v',      // Take video from first input
                '-map', '1:a',      // Take audio from second input (narration + music)
                '-c:v', 'copy',
                '-c:a', 'aac',
                '-b:a', '192k',
                '-shortest',
            ],
        });
    }

    async overlayLogo(
        videoPath: string,
        logoPath: string | undefined,
        outputPath: string
    ): Promise<void> {
        if (!logoPath) {
            await fsPromises.copyFile(videoPath, outputPath);
            return;
        }

        try {
            await fsPromises.access(logoPath);
        } catch {
            await fsPromises.copyFile(videoPath, outputPath);
            return;
        }

        await runFFmpeg({
            inputs: [videoPath, logoPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-filter_complex',
                '[1:v]scale=120:-1[logo];[0:v][logo]overlay=W-w-20:20',
                '-c:v', 'libx264',
                '-x264-params', 'threads=1',
                '-preset', 'veryfast',
                '-crf', '23',
                '-c:a', 'copy',
                '-movflags', '+faststart',
            ],
        });
    }

}

export default VideoAssemblyService;
