/**
 * Video Assembly Service
 * Assembles final video from clips, music, and branding using FFmpeg
 * 
 * SHORTS AUDIO STRUCTURE:
 * For Shorts (isShort=true), narration audio is automatically prepended with:
 * - 1.5s silence (visual hook phase)
 * - 0.3s soft UI click sound (transition)
 * - Original narration (explanation phase)
 * Total hook phase duration: 1.8s before narration starts
 */

import fsPromises from 'fs/promises';
import fs from 'fs';
import path from 'path';
import { runFFmpeg, getVideoDuration, checkFFmpeg } from './ffmpeg-utils';
import { Readable } from 'stream';
import { pipeline } from 'stream/promises';
import { ReadableStream } from 'stream/web'; // ADD THIS

export interface VideoAssemblyInput {
    jobId: string;
    videoId: string;
    clips: string[];
    clipTimings?: number[];
    animationStopTimes?: number[]; // Pre-calculated durations for each clip (from keyword extraction)
    narration?: string;          // Narration text for timing (fallback if no clipTimings)
    perSceneNarration: string[]; // Narration text per scene (for splitting audio if needed)
    narrationAudios?: string[];     // Path to narration audio file (generated by Gemini TTS)
    music?: string;
    branding?: {
        logo?: string;
        intro?: string;
        outro?: string;
    };
    isShort?: boolean;           // If true, output vertical 9:16 format for YouTube Shorts
}

export interface VideoAssemblyResult {
    videoId: string;
    outputPath: string;
    duration: number;
    clipCount: number;
}

export class VideoAssemblyService {
    private workDir: string;

    // Video format configurations
    private readonly LANDSCAPE_FORMAT = {
        width: 1920,
        height: 1080,
        scale: 'scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black',
    };

    private readonly VERTICAL_FORMAT = {
        width: 1080,
        height: 1920,
        // For vertical: crop center of landscape video, then scale to 1080x1920
        scale: 'scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920',
    };

    constructor(workDir?: string) {
        this.workDir = workDir || path.join(process.cwd(), 'videos');
    }

    /**
     * Get video filter string based on format (landscape or vertical for shorts)
     */
    private getVideoFilter(isShort: boolean = false): string {
        const format = isShort ? this.VERTICAL_FORMAT : this.LANDSCAPE_FORMAT;
        return `${format.scale},fps=30`;
    }

    private async downloadFile(url: string, outPath: string) {
        // Check if it's a local file path instead of URL
        if (!url.startsWith('http://') && !url.startsWith('https://')) {
            // It's a local file, just copy it
            await fsPromises.copyFile(url, outPath);
            return;
        }

        // It's a URL, download it
        const res = await fetch(url);
        if (!res.ok || !res.body) {
            throw new Error(`Failed to download ${url}`);
        }

        const webStream = res.body as unknown as ReadableStream;

        await pipeline(
            Readable.fromWeb(webStream),
            fs.createWriteStream(outPath)
        );
    }

    /**
     * Assemble a complete video from all assets
     */
    async assembleVideo(input: VideoAssemblyInput): Promise<VideoAssemblyResult> {
        console.error(`Starting video assembly for ${input.videoId}...`);

        const outputDir = path.join(this.workDir, input.videoId);
        await fsPromises.mkdir(outputDir, { recursive: true });

        console.error(`Number of narration audios: ${input.narrationAudios?.length}`);
        console.error(`Narration audios: ${input.narrationAudios}`);
        if (!input.narrationAudios || input.narrationAudios.length === 0) throw new Error("Narration audios required");

        /* -----------------------------------------
            2. Process each clip and concat on-the-fly
        ------------------------------------------ */
        const combinedPath = path.join(outputDir, "combined_video.mp4");
        let combinedExists = false;

        for (let i = 0; i < input.clips.length; i++) {

            const clipUrl = input.clips[i];

            const clipPath = path.join(outputDir, `clip_${i}.mp4`);
            const sceneAudio = path.join(outputDir, `scene_audio_${i}.wav`);
            const sceneVideo = path.join(outputDir, `scene_video_${i}.mp4`);

            console.error(`🎬 Processing scene ${i + 1}/${input.clips.length}...`);

            // Download clip
            console.error(`  ⬇️  Downloading scene ${i + 1} video...`);
            await this.downloadFile(clipUrl, clipPath);

            // Extract scene audio
            console.error(`  ⬇️  Downloading scene ${i + 1} audio...`);
            await this.downloadFile(input.narrationAudios[i], sceneAudio);

            // For Shorts: prepend silence + click before narration
            let finalSceneAudio = sceneAudio;
            if (input.isShort) {
                console.error(`  🔇 Adding hook silence + click for Shorts...`);
                const hookAudio = path.join(outputDir, `hook_audio_${i}.wav`);
                await this.prependHookAudioForShorts(sceneAudio, hookAudio);
                finalSceneAudio = hookAudio;
            }

            const sceneAudioDuration = await getVideoDuration(finalSceneAudio);
            const animationStop = input.animationStopTimes?.[i] ?? 0;
            const targetDuration = Math.max(animationStop + 0.5, sceneAudioDuration);

            console.error(`  🎞️  Normalizing scene ${i + 1} to ${targetDuration.toFixed(2)}s...`);
            // Normalize clip to target duration
            await this.normalizeClipWithDuration(
                clipPath,
                sceneVideo,
                targetDuration,
                input.isShort
            );

            // Attach audio to scene clip
            console.error(`  🔊 Attaching audio to scene ${i + 1}...`);
            const sceneWithAudio = path.join(outputDir, `scene_with_audio_${i}.mp4`);
            await this.addAudioToVideo(sceneVideo, finalSceneAudio, sceneWithAudio);

            // Concat immediately
            console.error(`  🔗 Concatenating scene ${i + 1} to combined video...`);
            if (!combinedExists) {
                await fsPromises.copyFile(sceneWithAudio, combinedPath);
                combinedExists = true;
            } else {
                const temp = path.join(outputDir, `temp_concat_${i}.mp4`);
                await this.concatClips([combinedPath, sceneWithAudio], temp);
                await fsPromises.rename(temp, combinedPath);
            }

            // Cleanup aggressively
            const cleanupFiles = [
                fsPromises.unlink(clipPath),
                fsPromises.unlink(sceneAudio),
                fsPromises.unlink(sceneVideo),
                fsPromises.unlink(sceneWithAudio),
            ];

            // Also cleanup hook audio if it was created (for Shorts)
            if (input.isShort && finalSceneAudio !== sceneAudio) {
                cleanupFiles.push(fsPromises.unlink(finalSceneAudio));
            }

            await Promise.allSettled(cleanupFiles);
        }

        /* -------------------------
            3. Add background music
        -------------------------- */

        console.error(`🎵 Adding background music to video...`);
        const combinedDuration = await getVideoDuration(combinedPath);
        let finalAudio: string;

        if (input.music) {
            console.error(`  📥 Preparing background music...`);
            finalAudio = await this.prepareBackgroundMusic(
                input.music,
                combinedDuration,
                outputDir
            );
        } else {
            console.error(`  🔇 No music provided, generating silence...`);
            finalAudio = path.join(outputDir, "silence.mp3");
            await this.generatePlaceholderNarration(combinedDuration, finalAudio);
        }

        const combinedWithMusic = path.join(outputDir, "combined_with_music.mp4");

        console.error(`  🎼 Mixing audio tracks...`);
        await runFFmpeg({
            inputs: [combinedPath, finalAudio],
            output: combinedWithMusic,
            args: [
                "-threads", "1",
                "-filter_complex",
                "[0:a]aresample=48000,pan=stereo|c0=c0|c1=c0[a0];" +
                "[1:a]aresample=48000,pan=stereo|c0=c0|c1=c1[a1];" +
                "[a0][a1]amix=inputs=2:weights=1 0.1:duration=first[a]",
                "-map", "0:v",
                "-map", "[a]",
                "-c:v", "copy",
                "-c:a", "aac",
                "-ar", "48000",
                "-ac", "2",
                "-b:a", "192k",
                "-shortest"
            ],
        });



        /* -------------------------
            4. Intro / Outro
        -------------------------- */

        console.error(`🎬 Checking for intro/outro branding...`);
        const normalizedDir = path.join(outputDir, 'normalized');
        await fsPromises.mkdir(normalizedDir, { recursive: true });

        let finalVideo = combinedWithMusic;

        if (!input.isShort && (input.branding?.intro || input.branding?.outro)) {
            console.error(`  🎞️  Adding intro/outro branding...`);
            const clips = await this.addIntroOutroWithOriginalAudio(
                combinedWithMusic,
                input.branding?.intro,
                input.branding?.outro,
                outputDir
            );

            const withBranding = path.join(outputDir, "with_branding.mp4");
            await this.concatClips(clips, withBranding);
            finalVideo = withBranding;
        }

        /* -------------------------
            5. Logo (optional)
        -------------------------- */

        console.error(`🏷️  Finalizing video output...`);
        const finalOutput = path.join(outputDir, "final.mp4");
        if (input.isShort) {
            console.error(`  📱 Overlaying logo for Shorts format...`);
            await this.overlayLogo(finalVideo, input.branding?.logo, finalOutput);
        } else {
            await fsPromises.copyFile(finalVideo, finalOutput);
        }

        const duration = await getVideoDuration(finalOutput);

        console.error(`✅ Video assembly complete! Duration: ${duration.toFixed(2)}s`);
        return {
            videoId: input.videoId,
            outputPath: finalOutput,
            duration,
            clipCount: input.clips.length,
        };
    }

    /**
     * Normalize clips with specific timing for each clip
     */
    async normalizeAndConcatClipsWithTiming(
        jobId: string,
        clips: string[],
        timings: number[],
        outputDir: string,
        isShort: boolean = false
    ): Promise<string> {

        const normalizedDir = path.join(outputDir, 'normalized');
        await fsPromises.mkdir(normalizedDir, { recursive: true });

        const downloadDir = path.join(outputDir, 'downloads');
        await fsPromises.mkdir(downloadDir, { recursive: true });

        const combinedVideoPath = path.join(outputDir, 'combined_clips.mp4');

        for (let i = 0; i < clips.length; i++) {
            const clipUrl = clips[i];
            const clipPath = path.join(downloadDir, `clip_${i + 1}.mp4`);

            console.error(`  Downloading clip ${i + 1}/${clips.length} from ${clipUrl}...`);
            await this.downloadFile(clipUrl, clipPath);
            const targetDuration = timings[i];
            const outputPath = path.join(normalizedDir, `clip_${i + 1}.mp4`);

            console.error(`  Normalizing clip ${i + 1}/${clips.length} (target: ${targetDuration.toFixed(2)}s)...`);
            await this.normalizeClipWithDuration(clipPath, outputPath, targetDuration, isShort);
            await fsPromises.unlink(clipPath); // Delete downloaded clip after normalization

            // Concatenate to combined video
            if (i > 0) {
                const tempCombinedPath = path.join(outputDir, `temp_combined_${i + 1}.mp4`);
                await this.concatClips([combinedVideoPath, outputPath], tempCombinedPath);
                await fsPromises.copyFile(tempCombinedPath, combinedVideoPath);
                await fsPromises.unlink(tempCombinedPath);
            }
            else await fsPromises.copyFile(outputPath, combinedVideoPath);

            await fsPromises.unlink(outputPath); // Delete normalized clip after concatenation
        }

        return combinedVideoPath;
    }

    async normalizeClipWithDuration(
        inputPath: string,
        outputPath: string,
        targetDuration: number,
        isShort: boolean = false
    ): Promise<void> {
        const videoFilter = this.getVideoFilter(isShort);

        let originalDuration: number;
        try {
            originalDuration = await getVideoDuration(inputPath);
        } catch {
            originalDuration = targetDuration;
        }

        const needsExtension = originalDuration < targetDuration;
        const extraDuration = Math.max(0, targetDuration - originalDuration);

        const vf = needsExtension
            ? `${videoFilter},tpad=stop_mode=clone:stop_duration=${extraDuration}`
            : videoFilter;

        await runFFmpeg({
            inputs: [inputPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-t', targetDuration.toString(),
                '-vf', vf,
                '-c:v', 'libx264',
                '-x264-params', 'threads=1',
                '-preset', 'veryfast',
                '-crf', '23',
                '-an', // no audio for stock clips
                '-movflags', '+faststart',
            ],
        });
    }

    async normalizeClip(inputPath: string, outputPath: string): Promise<void> {
        await runFFmpeg({
            inputs: [inputPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-vf', 'scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black,fps=30',
                '-c:v', 'libx264',
                '-x264-params', 'threads=1',
                '-preset', 'veryfast',
                '-crf', '23',
                '-c:a', 'aac',
                '-b:a', '128k',
                '-movflags', '+faststart',
            ],
        });
    }


    /**
     * Add intro and outro videos to the clip list
     */
    async addIntroOutro(
        clips: string[],
        introPath: string | undefined,
        outroPath: string | undefined,
        outputDir: string
    ): Promise<string[]> {
        const result: string[] = [];

        // Normalize intro if exists
        if (introPath) {
            const normalizedIntro = path.join(outputDir, 'normalized', 'intro.mp4');
            console.error('  Normalizing intro video...');
            await this.normalizeClip(introPath, normalizedIntro);
            result.push(normalizedIntro);
            console.error('  ✓ Intro added');
        }

        // Add main clips
        result.push(...clips);

        // Normalize outro if exists
        if (outroPath) {
            const normalizedOutro = path.join(outputDir, 'normalized', 'outro.mp4');
            console.error('  Normalizing outro video...');
            await this.normalizeClip(outroPath, normalizedOutro);
            result.push(normalizedOutro);
            console.error('  ✓ Outro added');
        }

        return result;
    }

    /**
     * Add intro and outro videos while preserving their original audio
     * Takes the main video (already with audio) and adds intro/outro around it
     */
    async addIntroOutroWithOriginalAudio(
        mainVideoPath: string,
        introPath: string | undefined,
        outroPath: string | undefined,
        outputDir: string
    ): Promise<string[]> {
        const result: string[] = [];

        // Normalize intro if exists (keeping original audio)
        if (introPath) {
            const normalizedIntro = path.join(outputDir, 'normalized', 'intro.mp4');
            console.error('  Normalizing intro video (preserving original audio)...');
            await this.normalizeClipWithAudio(introPath, normalizedIntro);
            result.push(normalizedIntro);
            console.error('  ✓ Intro added with original audio');
        }

        // Add main video (already has narration + music)
        result.push(mainVideoPath);

        // Normalize outro if exists (keeping original audio)
        if (outroPath) {
            const normalizedOutro = path.join(outputDir, 'normalized', 'outro.mp4');
            console.error('  Normalizing outro video (preserving original audio)...');
            await this.normalizeClipWithAudio(outroPath, normalizedOutro);
            result.push(normalizedOutro);
            console.error('  ✓ Outro added with original audio');
        }

        return result;
    }

    /**
     * Normalize a clip to 1920x1080 while preserving original audio
     */
    async normalizeClipWithAudio(inputPath: string, outputPath: string): Promise<void> {
        await runFFmpeg({
            inputs: [inputPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-vf', 'scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black,fps=30',
                '-c:v', 'libx264',
                '-preset', 'medium',
                '-crf', '23',
                '-c:a', 'aac',
                '-b:a', '192k',
                '-ar', '48000',
                '-ac', '2',
                '-movflags', '+faststart',
            ],
        });
    }


    /**
     * Prepare background music - loop to match video duration
     */
    async prepareBackgroundMusic(
        musicPath: string,
        videoDuration: number,
        outputDir: string
    ): Promise<string> {
        const outputPath = path.join(outputDir, 'background_music.mp3');

        console.error(`  Preparing background music to loop for ${videoDuration.toFixed(2)}s...`);

        // Always loop the music to match video duration
        await runFFmpeg({
            inputs: [musicPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-filter_complex', `aloop=loop=-1:size=2e+09,atrim=0:${videoDuration}`,
                '-c:a', 'libmp3lame',
                '-b:a', '192k',
                '-ar', '48000',
            ],
        });

        console.error('  ✓ Background music looped to match video duration');
        return outputPath;
    }

    /**
     * Mix narration audio with background music
     * Narration is primary, music is lowered to background level
     * Music loops throughout entire video with different volume for outro
     */
    async mixNarrationWithMusic(
        narrationPath: string,
        musicPath: string,
        videoDuration: number,
        outputDir: string
    ): Promise<string> {
        const outputPath = path.join(outputDir, 'final_audio.mp3');

        console.error(`  Mixing narration with background music...`);
        console.error(`  Narration: ${narrationPath}`);
        console.error(`  Music: ${musicPath}`);

        // Get narration duration
        const narrationDuration = await getVideoDuration(narrationPath);
        console.error(`  Narration duration: ${narrationDuration.toFixed(2)}s`);
        console.error(`  Total video duration: ${videoDuration.toFixed(2)}s`);

        // Calculate outro duration (time after narration ends)
        const outroDuration = Math.max(0, videoDuration - narrationDuration);
        console.error(`  Outro duration: ${outroDuration.toFixed(2)}s`);

        // Create filter complex for proper audio mixing:
        // 1. Loop music throughout entire video
        // 2. BGM at 15% during narration
        // 3. BGM at 30% during outro (after narration ends)
        const filterComplex = outroDuration > 0
            ? `[1:a]aloop=loop=-1:size=2e+09,atrim=0:${videoDuration}[music];` +
            `anullsrc=r=48000:cl=stereo,atrim=0:${outroDuration}[silence];` +
            `[0:a][silence]concat=n=2:v=0:a=1[narration_padded];` +
            `[music]asplit=2[music1][music2];` +
            `[music1]volume=0.15,atrim=0:${narrationDuration}[bgm_narration];` +
            `[music2]volume=0.30,atrim=${narrationDuration}:${videoDuration},asetpts=PTS-STARTPTS[bgm_outro];` +
            `[narration_padded][bgm_narration]amix=inputs=2:duration=first[main];` +
            `[main][bgm_outro]concat=n=2:v=0:a=1[out]`
            : `[1:a]aloop=loop=-1:size=2e+09,atrim=0:${videoDuration},volume=0.15[music];` +
            `[0:a][music]amix=inputs=2:duration=first[out]`;

        await runFFmpeg({
            inputs: [narrationPath, musicPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-filter_complex', filterComplex,
                '-map', '[out]',
                '-c:a', 'libmp3lame',
                '-b:a', '192k',
                '-ar', '48000',
            ],
        });

        console.error(`  ✓ Audio mixing complete (BGM loops throughout, louder at outro)`);
        return outputPath;
    }

    async concatClips(clips: string[], outputPath: string): Promise<void> {
        if (clips.length === 0) {
            throw new Error('No clips to concatenate');
        }

        if (clips.length === 1) {
            await fsPromises.copyFile(clips[0], outputPath);
            return;
        }

        const concatListPath = path.join(path.dirname(outputPath), 'concat_list.txt');
        const concatList = clips.map(c => `file '${c}'`).join('\n');
        await fsPromises.writeFile(concatListPath, concatList);

        await runFFmpeg({
            inputs: [],
            output: outputPath,
            args: [
                '-threads', '1',
                '-f', 'concat',
                '-safe', '0',
                '-i', concatListPath,
                '-c:v', 'libx264',
                '-x264-params', 'threads=1',
                '-preset', 'veryfast',
                '-crf', '23',
                '-c:a', 'aac',
                '-b:a', '128k',
                '-movflags', '+faststart',
            ],
        });
    }

    /**
     * Generate placeholder narration (silence) for the given duration
     */
    async generatePlaceholderNarration(duration: number, outputPath: string): Promise<void> {
        await runFFmpeg({
            inputs: [],
            output: outputPath,
            args: [
                '-threads', '1',
                '-f', 'lavfi',
                '-i', `anullsrc=r=44100:cl=stereo`,
                '-t', duration.toString(),
                '-c:a', 'libmp3lame',
                '-b:a', '128k',
            ],
        });
    }

    /**
     * Prepend silence + click sound before narration for Shorts hook phase
     * Hook phase: 1.5s silence + 0.3s click = 1.8s total before narration
     */
    async prependHookAudioForShorts(
        narrationPath: string,
        outputPath: string
    ): Promise<void> {
        const HOOK_DURATION = 1.5; // Silence for visual hook
        const HOOK_PAUSE = 0.3;    // Click sound duration

        // Path to the soft UI click sound
        const clickSoundPath = path.join(__dirname, '../../assets/music/soft-ui-click.wav');

        console.error(`    Prepending ${HOOK_DURATION}s silence + ${HOOK_PAUSE}s click...`);

        // Convert narration to WAV for concatenation (same format as silence/click)
        const narrationWavPath = path.join(path.dirname(outputPath), 'narration_temp.wav');
        await runFFmpeg({
            inputs: [narrationPath],
            output: narrationWavPath,
            args: [
                '-c:a', 'pcm_s16le',
                '-ar', '48000',
                '-ac', '2',
            ],
        });

        // Create silence audio using -t flag (compatible with older FFmpeg)
        const silencePath = path.join(path.dirname(outputPath), 'hook_silence.wav');
        await runFFmpeg({
            inputs: [],
            output: silencePath,
            args: [
                '-f', 'lavfi',
                '-i', 'anullsrc=r=48000:cl=stereo',
                '-t', HOOK_DURATION.toString(),
                '-c:a', 'pcm_s16le',
            ],
        });

        // Trim/pad click sound to exact HOOK_PAUSE duration
        const clickPath = path.join(path.dirname(outputPath), 'hook_click.wav');
        await runFFmpeg({
            inputs: [clickSoundPath],
            output: clickPath,
            args: [
                '-t', HOOK_PAUSE.toString(),
                '-af', 'apad',
                '-c:a', 'pcm_s16le',
            ],
        });

        // Concatenate: silence + click + narration
        const concatListPath = path.join(path.dirname(outputPath), 'hook_concat.txt');
        const concatList = `file '${silencePath}'\nfile '${clickPath}'\nfile '${narrationWavPath}'`;
        await fsPromises.writeFile(concatListPath, concatList);

        await runFFmpeg({
            inputs: [],
            output: outputPath,
            args: [
                '-f', 'concat',
                '-safe', '0',
                '-i', concatListPath,
                '-c:a', 'pcm_s16le',
            ],
        });

        // Cleanup temporary files
        await Promise.allSettled([
            fsPromises.unlink(silencePath),
            fsPromises.unlink(clickPath),
            fsPromises.unlink(narrationWavPath),
            fsPromises.unlink(concatListPath),
        ]);
    }

    /**
     * Add audio track to video (replaces existing audio)
     * Ensures output duration matches the longer of video or audio
     */
    async addAudioToVideo(
        videoPath: string,
        audioPath: string,
        outputPath: string
    ): Promise<void> {
        // Get durations of both inputs
        const videoDuration = await getVideoDuration(videoPath);
        const audioDuration = await getVideoDuration(audioPath);
        const maxDuration = Math.max(videoDuration, audioDuration);

        console.error(`    Video: ${videoDuration.toFixed(2)}s, Audio: ${audioDuration.toFixed(2)}s, Output: ${maxDuration.toFixed(2)}s`);

        await runFFmpeg({
            inputs: [videoPath, audioPath],
            output: outputPath,
            args: [
                "-threads", "1",
                "-filter_complex",
                `[0:v]tpad=stop_mode=clone:stop_duration=${Math.max(0, audioDuration - videoDuration)}[v];` +
                `[1:a]apad[a]`,
                "-map", "[v]",
                "-map", "[a]",
                "-c:v", "libx264",
                "-preset", "veryfast",
                "-c:a", "aac",
                "-b:a", "192k",
                "-t", maxDuration.toString(),
            ],
        });
    }

    async overlayLogo(
        videoPath: string,
        logoPath: string | undefined,
        outputPath: string
    ): Promise<void> {
        if (!logoPath) {
            await fsPromises.copyFile(videoPath, outputPath);
            return;
        }

        try {
            await fsPromises.access(logoPath);
        } catch {
            await fsPromises.copyFile(videoPath, outputPath);
            return;
        }

        await runFFmpeg({
            inputs: [videoPath, logoPath],
            output: outputPath,
            args: [
                '-threads', '1',
                '-filter_complex',
                '[1:v]scale=120:-1[logo];[0:v][logo]overlay=W-w-20:20',
                '-c:v', 'libx264',
                '-x264-params', 'threads=1',
                '-preset', 'veryfast',
                '-crf', '23',
                '-c:a', 'copy',
                '-movflags', '+faststart',
            ],
        });
    }

}

export default VideoAssemblyService;
